// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNJg_m5XGgIi0ic4xAuXqwX-obxoYjJxA',
    appId: '1:439730987559:web:98c3d849331e0090ef2402',
    messagingSenderId: '439730987559',
    projectId: 'chatapp-4d249',
    authDomain: 'chatapp-4d249.firebaseapp.com',
    storageBucket: 'chatapp-4d249.appspot.com',
    measurementId: 'G-ZMC1XNT54V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBq2Jb9IOv1epZcNUmOXl0zYPltQhY9lI',
    appId: '1:439730987559:android:3106f6ee6f4a8d7bef2402',
    messagingSenderId: '439730987559',
    projectId: 'chatapp-4d249',
    storageBucket: 'chatapp-4d249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSDg495WFJMd63VSAWpiC-YVyvY-9XHZs',
    appId: '1:439730987559:ios:b947fddcfbdb2112ef2402',
    messagingSenderId: '439730987559',
    projectId: 'chatapp-4d249',
    storageBucket: 'chatapp-4d249.appspot.com',
    iosBundleId: 'chatapp1demo',
  );
}
